### ISSUE TITLE
How to jump to a new line

### ISSUE THREAD

**Issue by Esqarrouth** [Dvergar/dopresskit-static#6]
While writing the description I couldn't jump to a new line. Tried <\br> \n 

Also these solutions didn't work for me: http://stackoverflow.com/questions/10917555/adding-a-new-line-break-tag-in-xml

**Comment by Esqarrouth** [comment]
@jonongjs @Rastagong @Dvergar any ideas?

**Comment by jonongjs** [comment]
A temporary solution would be to use `&lt;br&gt;` wherever you need a newline.

Of course, this is hacky and not ideal. It would be better to get the Python script to recognize a special tag, or possibly replace newlines within the text nodes with the `<br>` tag.

**Comment by Esqarrouth** [comment]
Thanks!

Its hacky but I see no downsides except remembering/reading.
