### ISSUE TITLE
How to put a header image?

### ISSUE THREAD

**Issue by Esqarrouth** [Dvergar/dopresskit-static#7]
Like in here: http://prntscr.com/etxatv

**Comment by Esqarrouth** [comment]
@jonongjs @Rastagong @Dvergar any ideas?

**Comment by jonongjs** [comment]
Have you tried creating an `images/` directory alongside your company's `data.xml`, and saving your header as `images/header.png`?

**Comment by Esqarrouth** [comment]
Oh of course.. Thanks!
